spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 12MB
  h2:
    console:
      enabled: true
      path: /h2
        
        
        
